spring:
  profiles:
    active: prod

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
        show_sql: true
    open-in-view: false

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

jwt:
  secret: ${jwt_secret}
  expiry: ${jwt.expiry}

client-id: ${client-id}
client-secret: ${client-secret}

token:
  expire:
    time: ${token_expire_time}